#!/usr/bin/env python3

import requests
import sys

# Query Overpass for all national country relations and their admin_centre nodes
query = """
[out:json][timeout:180];
rel["admin_level"="2"]["ISO3166-1"]->.countries;
.countries out;
node(r.countries:"admin_centre")["capital"="yes"]->.capitals;
.capitals out body;
"""

print("Fetching global test locations with precise country mapping from OpenStreetMap...")
try:
    headers = {'User-Agent': 'GeminiCLI-TestDataFetcher/1.0'}
    response = requests.post("https://overpass-api.de/api/interpreter", data={'data': query}, headers=headers)
    response.raise_for_status()
    data = response.json()
except Exception as e:
    print(f"Error during request to Overpass API: {e}", file=sys.stderr)
    sys.exit(1)

elements = data.get('elements', [])
if not elements:
    print("No locations found.")
    sys.exit(0)

# Build a mapping of Node ID -> Country ISO Code from relations
node_to_country = {}
for e in elements:
    if e.get('type') == 'relation':
        iso_code = e.get('tags', {}).get('ISO3166-1')
        if not iso_code:
            continue
        for member in e.get('members', []):
            if member.get('type') == 'node' and member.get('role') == 'admin_centre':
                node_to_country[member.get('ref')] = iso_code

# Separate nodes
nodes = [e for e in elements if e.get('type') == 'node']

print(f"Mapped {len(node_to_country)} capitals via relations. Found {len(nodes)} total nodes. Preparing SQL...")

# Target a dedicated file for global locations
target_file = "03-global-locations.sql"

try:
    # Collect all values for a single bulk INSERT
    values = []
    for node in nodes:
        tags = node.get('tags', {})
        node_id = node.get('id')
        
        country_code = (node_to_country.get(node_id) or 
                        tags.get('addr:country') or 
                        tags.get('is_in:country_code') or
                        'XX')
        country_code = country_code[:2].upper()
        
        if country_code == 'XX':
            continue

        name = tags.get('name:en') or tags.get('name', 'Unknown Location')
        clean_name = name.replace("'", "''")
        
        city = tags.get('addr:city') or name
        clean_city = city.replace("'", "''")
        
        address_line = tags.get('addr:street') or f"Central {name}"
        clean_address = address_line.replace("'", "''")
        
        lat = node.get('lat')
        lon = node.get('lon')
        
        if lat is None or lon is None:
            continue

        value_row = (f"('{clean_name}', '{clean_address}', '{clean_city}', '{country_code}', "
                     f"ST_GeographyFromText('POINT({lon} {lat})'))")
        values.append(value_row)

    if values:
        with open(target_file, "w", encoding="utf-8") as sql_file:
            sql_file.write("-- Global Test Locations (Generated by fetch-global-test-locations.py)\n")
            sql_file.write("INSERT INTO locations (name, address_line, city, country_code, geom) VALUES\n")
            sql_file.write(",\n".join(values))
            sql_file.write(";\n")
        print(f"Success! Generated {len(values)} locations in {target_file}.")
    else:
        print("No clean locations found to write.")

except Exception as e:
    print(f"Error processing data: {e}", file=sys.stderr)
    sys.exit(1)
