micronautVersion=5.0.5
jtsVersion=1.20.0
groovySqlVersion=4.0.18
datafakerVersion=2.4.2
commonsCompressVersion=1.28.0
kaijuVersion=0.0.2
systemProp.sonar.projectKey=PeanutButter-Unicorn_kaiju
systemProp.sonar.organization=peanutbutter-unicorn
systemProp.sonar.projectName=Kaiju
systemProp.sonar.host.url=https://sonarcloud.io
systemProp.sonar.tests=src/test/groovy
